name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      id-token: write
    strategy:
      matrix:
        include:
          # Four images are created:
          # - Multi-arch manifest for: amd64 and arm64
          - tag-suffix: ""
            platforms: linux/amd64,linux/arm64
          # - arm64 manifest
          - tag-suffix: "-arm64"
            platforms: linux/arm64
          # - amd64 manifest
          - tag-suffix: "-amd64"
            platforms: linux/amd64
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push all image variations
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: shell
        tag: ${{ github.ref_name }}${{ matrix.tag-suffix }}
        platforms: ${{ matrix.platforms }}

        public-registry: ghcr.io
        public-repo: ${{ github.repository }}
        public-username: ${{ github.actor }}
        public-password: ${{ secrets.GITHUB_TOKEN }}
        
        push-to-prime: false
