name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write # Permission to push to GitHub Packages

env:
  PUBLIC_REGISTRY: ghcr.io

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - s390x manifest
          - tag-suffix: "-s390x"
            platforms: linux/s390x
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.PUBLIC_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push all image variations
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: ${{ vars.IMAGE_NAME || 'shell' }}
        tag: ${{ github.ref_name }}${{ matrix.tag-suffix }}
        platforms: "linux/s390x"

        public-registry: ${{ env.PUBLIC_REGISTRY }}
        public-repo: ${{ vars.REPO || github.repository_owner }}
        public-username: ${{ github.actor }}
        public-password: ${{ secrets.GITHUB_TOKEN }}
        
        push-to-public: true
        push-to-prime: false
