name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GHCR
      id-token: write
    strategy:
      matrix:
        platform:
          - linux/s390x

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push Docker images to GHCR
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: ${{ matrix.platform }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/shell:${{ github.ref_name }}
        push: true
