name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: info
        type: choice
        options:
          - info
          - debug
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      configMigration:
        description: "Toggle PRs for config migration"
        required: false
        default: "true"
        type: choice
        options:
          - "false"
          - "true"
      renovateConfig:
        description: "Define a custom renovate config file"
        required: false
        default: ".github/renovate.json"
        type: string

  schedule:
    - cron: '30 4,6 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.0
        with:
          configurationFile: ${{ inputs.renovateConfig || '.github/renovate.json' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          renovate-version: latest
